import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8f9fa',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        paddingTop: 40,
        backgroundColor: '#009688',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 5,
        zIndex: 10,
    },
    headerTitle: {
        color: '#fff',
        fontSize: 22,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    drawer: {
        position: 'absolute',
        top: 90,
        left: 0,
        width: '70%',
        height: '100%',
        backgroundColor: '#ffffff',
        zIndex: 100,
        elevation: 10,
        paddingVertical: 20,
        borderTopRightRadius: 15,
        borderBottomRightRadius: 15,
        shadowColor: '#000',
        shadowOffset: { width: 5, height: 0 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
    },
    drawerItem: {
        paddingVertical: 18,
        paddingHorizontal: 25,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    drawerText: {
        fontSize: 16,
        color: '#4a4a4a',
        fontWeight: '500',
    },
    content: {
        flex: 1,
        padding: 10,
    },
    booksContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    bookCard: {
        width: '48%',
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 15,
        marginBottom: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 6,
        elevation: 3,
        transform: [{ scale: 1 }],
    },
    bookTitle: {
        fontSize: 16,
        fontWeight: '700',
        marginBottom: 6,
        color: '#333',
        lineHeight: 22,
    },
    bookAuthor: {
        fontSize: 14,
        color: '#555',
        marginBottom: 4,
        fontStyle: 'italic',
    },
    bookInfo: {
        fontSize: 12,
        color: '#666',
        marginBottom: 3,
    },
    statusContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 8,
    },
    statusDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        marginRight: 6,
    },
    available: {
        backgroundColor: '#4caf50',
    },
    unavailable: {
        backgroundColor: '#f44336',
    },
    statusText: {
        fontSize: 12,
        fontWeight: '500',
    },
    borrowButton: {
        backgroundColor: '#009688',
        paddingVertical: 8,
        borderRadius: 20,
        marginTop: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    borrowButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 14,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    emptyText: {
        textAlign: 'center',
        marginTop: 50,
        fontSize: 16,
        color: '#888',
    },
    bookCardPressed: {
        transform: [{ scale: 0.98 }],
        opacity: 0.9,
    },
});
